decl
    = fn_decl
    | type_decl
    | import_decl;

import_decl
    = "import", import_path;

import_path
    = ident, { ".", ident };

type_decl
    = "type", ident, [ generic_params ], "=", type_body;

type_body
    = struct_decl
    | trait_decl
    | enum_decl
    | type;

trait_decl
    = "trait", "{", [ fn_decl, { ";", fn_decl }, [ ";" ] ], "}";

enum_decl
    = "enum", "{", [ enum_variant, { ",", enum_variant }, [ "," ] ], "}";

enum_variant
    = ident;

struct_decl
    = "struct", "{", [ struct_field, { ",", struct_field }, [ "," ] ], "}";

struct_field
    = ident, ":", type;

stmt
    = local
    | expr;

local
    = ( "let"
    | "var"
    | "const" ), ident, [ ":", type ], [ "=", expr ];

block
    = "{", [ stmt, { ";", stmt }, [ "," ] ], "}";

fn_decl
    = [ "inline" ], "fn", ident, [ generic_params ], fn_params, [ type ], block;

fn_params
    = "(", [ fn_param, { ",", fn_param }, [ "," ] ], ")";

fn_param
    = ident, ":", type;

generic_params
    = "[", [ generic_param, { ",", generic_param }, [ "," ] ], "]";

generic_param
    = ident, [ ":", type ];

type
    = array, ptr, path;

array
    = { "[", usize, "]" };

ptr
    = { "*"
    | ( "*", "const" ) };

path
    = segment, { ".", segment };

segment
    = ident, generic_args;

generic_args
    = "[", [ type, { ",", type }, [ "," ] ], "]";

expr
    = if_stmt
    | assign;

assign
    = logic_or, [ assign_kind, expr ];

assign_kind
    = "="
    | "+="
    | "-="
    | "*="
    | "/=";

logic_or
    = logic_and, { "||", logic_and };

logic_and
    = comparation, { "&&", comparation };

comparation
    = addition, [ ( "=="
    | "!="
    | "<="
    | ">="
    | "<"
    | ">" ), addition ];

addition
    = multiplication, { ( "+"
    | "-" ), multiplication };

multiplication
    = division, { "*", division };

division
    = unary, { "/", unary };

unary
    = ( "*"
    | "&"
    | "!"
    | "-" ), cast
    | cast;

cast
    = factor, [ "as", type ];

factor
    = primary, { accessor };

primary
    = integer
    | float
    | string
    | bool
    | ( "(", expr, ")" )
    | struct_init
    | path;

struct_init
    = path, "{", [ struct_init_field, { ",", struct_init_field }, [ "," ] ], "}";

struct_init_field
    = ".", ident, "=", expr;

accessor
    = call
    | field_access;

call
    = "(", [ expr, { ",", expr }, [ "," ] ], ")";

field_access
    = ".", segment;

if_stmt
    = "if", expr, block, [ "else", ( if_stmt
    | block ) ];